// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class DateTimeLocationStatus
    {
        public DateTimeLocationStatus()
        {
            DateTimeLocation = new HashSet<DateTimeLocation>();
        }

        public int StatusId { get; set; }
        public string StatusName { get; set; }

        public virtual ICollection<DateTimeLocation> DateTimeLocation { get; set; }
    }
}