// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Decoration
    {
        public Decoration()
        {
            DecorationProduct = new HashSet<DecorationProduct>();
            Event = new HashSet<Event>();
        }

        public int DecorationId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Combo { get; set; }
        public string Image { get; set; }

        public virtual ICollection<DecorationProduct> DecorationProduct { get; set; }
        public virtual ICollection<Event> Event { get; set; }
    }
}