// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Entertainment
    {
        public Entertainment()
        {
            EntertainmentProduct = new HashSet<EntertainmentProduct>();
            Event = new HashSet<Event>();
        }

        public int EntertainmentId { get; set; }
        public bool Status { get; set; }
        public decimal Total { get; set; }

        public virtual ICollection<EntertainmentProduct> EntertainmentProduct { get; set; }
        public virtual ICollection<Event> Event { get; set; }
    }
}