// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class EntertainmentProduct
    {
        public int EntertainmentId { get; set; }
        public int ProductId { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }

        public virtual Entertainment Entertainment { get; set; }
        public virtual Game Product { get; set; }
        public virtual Show ProductNavigation { get; set; }
    }
}