// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class EventType
    {
        public EventType()
        {
            Event = new HashSet<Event>();
            Script = new HashSet<Script>();
        }

        public int EventTypeId { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<Script> Script { get; set; }
    }
}