// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Event
    {
        public Event()
        {
            DateTimeLocation = new HashSet<DateTimeLocation>();
            Entertainment = new HashSet<Entertainment>();
            Menu = new HashSet<Menu>();
        }

        public int EventId { get; set; }
        public int ScriptId { get; set; }
        public int RoomId { get; set; }
        public int DecorationId { get; set; }
        public int EventTypeId { get; set; }
        public int OrderId { get; set; }

        public virtual Decoration Decoration { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual EventOrder Order { get; set; }
        public virtual Room Room { get; set; }
        public virtual Script Script { get; set; }
        public virtual ICollection<DateTimeLocation> DateTimeLocation { get; set; }
        public virtual ICollection<Entertainment> Entertainment { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
    }
}