// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Feedback
    {
        public int EventBookerId { get; set; }
        public int EventId { get; set; }
        public int Vote { get; set; }
        public string Message { get; set; }
        public DateTime Date { get; set; }
        public string Reply { get; set; }
        public bool Status { get; set; }
    }
}