// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class FoodType
    {
        public FoodType()
        {
            Food = new HashSet<Food>();
        }

        public int FoodTypeId { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }

        public virtual ICollection<Food> Food { get; set; }
    }
}