// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Menu
    {
        public Menu()
        {
            MenuDrink = new HashSet<MenuDrink>();
            MenuProduct = new HashSet<MenuProduct>();
        }

        public int MenuId { get; set; }
        public bool Status { get; set; }
        public int EventId { get; set; }
        public decimal PriceTotal { get; set; }

        public virtual Event Event { get; set; }
        public virtual ICollection<MenuDrink> MenuDrink { get; set; }
        public virtual ICollection<MenuProduct> MenuProduct { get; set; }
    }
}