// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class MenuDrink
    {
        public int MenuId { get; set; }
        public int DrinkId { get; set; }
        public int Quantity { get; set; }
        public long Price { get; set; }

        public virtual Drink Drink { get; set; }
        public virtual Menu Menu { get; set; }
    }
}