// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Payment
    {
        public Payment()
        {
            Refund = new HashSet<Refund>();
        }

        public int PaymentId { get; set; }
        public int EventOrderId { get; set; }
        public decimal Amount { get; set; }
        public DateTime Date { get; set; }
        public bool Status { get; set; }

        public virtual EventOrder EventOrder { get; set; }
        public virtual ICollection<Refund> Refund { get; set; }
    }
}