// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Room
    {
        public Room()
        {
            DateTimeLocation = new HashSet<DateTimeLocation>();
            Event = new HashSet<Event>();
        }

        public int RoomId { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public bool Status { get; set; }
        public byte[] Image { get; set; }
        public string Description { get; set; }

        public virtual ICollection<DateTimeLocation> DateTimeLocation { get; set; }
        public virtual ICollection<Event> Event { get; set; }
    }
}