// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Show
    {
        public Show()
        {
            EntertainmentProduct = new HashSet<EntertainmentProduct>();
        }

        public int ShowId { get; set; }
        public decimal Price { get; set; }
        public string Name { get; set; }
        public string Light { get; set; }
        public string Sound { get; set; }
        public string Singer { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public bool Status { get; set; }

        public virtual ICollection<EntertainmentProduct> EntertainmentProduct { get; set; }
    }
}