// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FamilyEventt.Models
{
    public partial class Staff
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public bool Status { get; set; }

        public virtual Role Role { get; set; }
    }
}